#
# Copyright © 2020 – 2024 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

---
- job:
    name: unit-test
    description: Run Toolbx's unit tests declared in Meson
    timeout: 1800
    nodeset:
      nodes:
        - name: fedora-rawhide
          label: cloud-fedora-rawhide
    pre-run: playbooks/setup-env.yaml
    run: playbooks/unit-test.yaml

- job:
    name: unit-test-migration-path-for-coreos-toolbox
    description: Run Toolbx's unit tests declared in Meson when built with -Dmigration_path_for_coreos_toolbox
    timeout: 600
    nodeset:
      nodes:
        - name: centos-9-stream
          label: cloud-centos-9-stream
    pre-run: playbooks/setup-env-migration-path-for-coreos-toolbox.yaml
    run: playbooks/unit-test.yaml

- job:
    name: unit-test-restricted
    description: Run Toolbx's unit tests declared in Meson in a restricted build environment
    timeout: 1800
    nodeset:
      nodes:
        - name: fedora-rawhide
          label: cloud-fedora-rawhide
    pre-run: playbooks/setup-env-restricted.yaml
    run: playbooks/unit-test.yaml

- job:
    name: system-test-fedora-rawhide
    description: Run Toolbx's system tests in Fedora Rawhide
    timeout: 4800
    nodeset:
      nodes:
        - name: fedora-rawhide
          label: cloud-fedora-rawhide
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- job:
    name: system-test-fedora-40
    description: Run Toolbx's system tests in Fedora 40
    timeout: 3600
    nodeset:
      nodes:
        - name: fedora-40
          label: cloud-fedora-40
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- job:
    name: system-test-fedora-39
    description: Run Toolbx's system tests in Fedora 39
    timeout: 3600
    nodeset:
      nodes:
        - name: fedora-39
          label: cloud-fedora-39
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- job:
    name: system-test-fedora-38
    description: Run Toolbx's system tests in Fedora 38
    timeout: 3600
    nodeset:
      nodes:
        - name: fedora-38
          label: cloud-fedora-38
    pre-run: playbooks/setup-env.yaml
    run: playbooks/system-test.yaml

- project:
    periodic:
      jobs:
        - system-test-fedora-rawhide
        - system-test-fedora-40
        - system-test-fedora-39
        - system-test-fedora-38
    check:
      jobs:
        - unit-test
        - unit-test-migration-path-for-coreos-toolbox
        - unit-test-restricted
        - system-test-fedora-rawhide
        - system-test-fedora-40
        - system-test-fedora-39
        - system-test-fedora-38
    gate:
      jobs:
        - unit-test
        - unit-test-migration-path-for-coreos-toolbox
        - unit-test-restricted
        - system-test-fedora-rawhide
        - system-test-fedora-40
        - system-test-fedora-39
        - system-test-fedora-38
